### PR TITLE
Implement F5 "class" command

### PR DESCRIPTION
**Pull request by jamespic**
I've partially implemented the "class" command (https://devcentral.f5.com/wiki/irules.class.ashx). Our iRules use it quite a bit, and trying to handle it with mocks was becoming painful.

### CODE REVIEW

**Comment by landro** [comment]
Looks great @jamespic ! I think it would make sense to add some documentation to the readme too - could you do that, please?

**Comment by Strekerud** [comment]
Any chance of this being merged in? We might use testcl, but we depend on class matching a lot.

**Comment by jamespic** [comment]
Sorry, this is my bad. @landro asked me to add some documentation, and it kind of fell off my radar. There's some basic documentation now, so it's hopefully closer to being mergable.

**Comment by landro** [comment]
Hi there! I'll see if I can get the merge in tonight. Stay tuned.

**Pull request merged**
