### PR TITLE
Add support to advanced pool verification

### PR DESCRIPTION
**Pull request by gszeliga**
I ran into an issue where `endstate` would not do the job to verify the last `pool` set by an `iRule` when wrapped in a `catch` expression.

This PR attempts to address that by enriching the available building blocks with the following new statements:

- `given_pools`: where you can declare all available pools to be used
- `endstate_pool`: an easy way to get back the last pool set by the iRule

This way, you can have things like:

`verify "Final pool is the expected one after a match" "go_to_bar" eq { endstate_pool }`

which is super awesome to have handy!

Let me know what you think

### CODE REVIEW

**Comment by landro** [comment]
I'll try to ave a look at this PR within the next few days, @gszeliga !

**Comment by landro** [comment]
I'm having seeing a regression in examples/example_irule_pool_verification.tcl
Could you make sure it doesn't break, @gszeliga ?

**Comment by gszeliga** [comment]
Hey @landro! Sorry for the buggy example. It should be fine now!

**Comment by gszeliga** [comment]
@landro It's been a while since I heard from you. Is there anything I can do to unblock this PR? Thanks!

**Comment by landro** [comment]
Guillermo,
Thanks for reminding me. I’ve been very busy for the past few weeks - I’ll try to get a look at it during this week.

**Comment by landro** [comment]
@gszeliga I'm still getting errors:

``` ➜  TesTcl git:(gszeliga-support-advanced-pool-verification) jtcl examples/example_irule_pool_verification.tcl

**************************************************************************
* it should set the right pool when available
**************************************************************************
-> Test failure!!
-> -> Verification 'Final pool is the expected one after a match' failed - expression: {go_to_bar} eq {}
error     Verification 'Final pool is the expected one after a match' failed - expression: {go_to_bar} eq {}

**************************************************************************
* it should fallback to default LB::server default pool if nothing matches
**************************************************************************
-> Test failure!!
-> -> Verification 'Final pool should be defaults' failed - expression: {fallback} eq {}
error     Verification 'Final pool should be defaults' failed - expression: {fallback} eq {}```

**Comment by gszeliga** [comment]
Hey @landro !

Have you checked your `TCLLIBPATH`? It might be pointing to the wrong version.

I ran the tests again and they look fine this time :(

```
❯ jtcl examples/example_irule_pool_verification.tcl

**************************************************************************
* it should set the right pool when available
**************************************************************************
verification of 'Final pool is the expected one after a match' done.
-> Test ok

**************************************************************************
* it should fallback to default LB::server default pool if nothing matches
**************************************************************************
verification of 'Final pool should be defaults' done.
-> Test ok
```

**Pull request merged**
